// Auth types
export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const LOGOUT = 'LOGOUT'
export const AUTHORIZE = 'AUTHORIZE'
export const CLEAR_LOGIN = 'CLEAR_LOGIN'

export const CREATE_PROFILE = 'CREATE_PROFILE'
export const CREATE_PROFILE_SUCCESS = 'CREATE_PROFILE_SUCCESS'
export const CREATE_PROFILE_FAILURE = 'CREATE_PROFILE_FAILURE'

export const VERIFY = 'VERIFY'
export const VERIFY_SUCCESS = 'VERIFY_SUCCESS'
export const VERIFY_SUCCESS_AUTH = 'VERIFY_SUCCESS_AUTH'
export const VERIFY_FAILURE = 'VERIFY_FAILURE'

// User Types
export const FETCH_PROFILE = 'FETCH_PROFILE'
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS'
export const FETCH_PROFILE_FAILURE = 'FETCH_PROFILE_FAILURE'

export const EDIT_AVATAR = 'EDIT_AVATAR'
export const EDIT_AVATAR_SUCCESS = 'EDIT_AVATAR_SUCCESS'
export const EDIT_AVATAR_FAILURE = 'EDIT_AVATAR_FAILURE'

export const EDIT_NAME = 'EDIT_NAME'
export const EDIT_NAME_SUCCESS = 'EDIT_NAME_SUCCESS'
export const EDIT_NAME_FAILURE = 'EDIT_NAME_FAILURE'

// Contact Types
export const FETCH_CONTACT_LIST = 'FETCH_CONTACT_LIST'
export const FETCH_CONTACT_LIST_SUCCESS = 'FETCH_CONTACT_LIST_SUCCESS'
export const FETCH_CONTACT_LIST_FAILURE = 'FETCH_CONTACT_LIST_FAILURE'

export const FETCH_CONTACT = 'FETCH_CONTACT'
export const FETCH_CONTACT_SUCCESS = 'FETCH_CONTACT_SUCCESS'
export const FETCH_CONTACT_FAILURE = 'FETCH_CONTACT_FAILURE'

export const UNLOCK_CONTACT = 'UNLOCK_CONTACT'
export const UNLOCK_CONTACT_SUCCESS = 'UNLOCK_CONTACT_SUCCESS'
export const UNLOCK_CONTACT_FAILURE = 'UNLOCK_CONTACT_FAILURE'

export const ADD_TAG = 'ADD_TAG'
export const REMOVE_TAG = 'REMOVE_TAG'
export const TAG_ERROR = 'TAG_ERROR'

export const ADD_SHARE = 'ADD_SHARE'
export const REMOVE_SHARE = 'REMOVE_SHARE'
export const SHARE_ERROR = 'SHARE_ERROR'

export const DECLINE_PENDING = 'DECLINE_PENDING'
export const DECLINE_PENDING_SUCCESS = 'DECLINE_PENDING_SUCCESS'
export const DECLINE_PENDING_FAILURE = 'DECLINE_PENDING_FAILURE'

export const DELETE_CONTACT = 'DELETE_CONTACT'
export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS'
export const DELETE_CONTACT_FAILURE = 'DELETE_CONTACT_FAILURE'

// Group Types
export const FETCH_GROUP_LIST = 'FETCH_GROUP_LIST'
export const FETCH_GROUP_LIST_SUCCESS = 'FETCH_GROUP_LIST_SUCCESS'
export const FETCH_GROUP_LIST_FAILURE = 'FETCH_GROUP_LIST_FAILURE'

export const FETCH_GROUP = 'FETCH_GROUP'
export const FETCH_GROUP_SUCCESS = 'FETCH_GROUP_SUCCESS'
export const FETCH_GROUP_FAILURE = 'FETCH_GROUP_FAILURE'

export const CREATE_GROUP = 'CREATE_GROUP'
export const CREATE_GROUP_SUCCESS = 'CREATE_GROUP_SUCCESS'
export const CREATE_GROUP_FAILURE = 'CREATE_GROUP_FAILURE'

export const EDIT_GROUP_NAME = 'EDIT_GROUP_NAME'
export const EDIT_GROUP_NAME_SUCCESS = 'EDIT_GROUP_NAME_SUCCESS'
export const EDIT_GROUP_NAME_FAILURE = 'EDIT_GROUP_NAME_FAILURE'

export const EDIT_GROUP_AVATAR = 'EDIT_GROUP_AVATAR'
export const EDIT_GROUP_AVATAR_SUCCESS = 'EDIT_GROUP_AVATAR_SUCCESS'
export const EDIT_GROUP_AVATAR_FAILURE = 'EDIT_GROUP_AVATAR_FAILURE'

export const INVITE_MEMBERS = 'INVITE_MEMBERS'
export const INVITE_MEMBERS_SUCCESS = 'INVITE_MEMBERS_SUCCESS'
export const INVITE_MEMBERS_FAILURE = 'INVITE_MEMBERS_FAILURE'

export const REMOVE_MEMBER = 'REMOVE_MEMBERS'
export const REMOVE_MEMBER_SUCCESS = 'REMOVE_MEMBERS_SUCCESS'
export const REMOVE_MEMBER_FAILURE = 'REMOVE_MEMBERS_FAILURE'

export const ADD_MODERATOR = 'ADD_MODERATORS'
export const ADD_MODERATOR_SUCCESS = 'ADD_MODERATORS_SUCCESS'
export const ADD_MODERATOR_FAILURE = 'ADD_MODERATORS_FAILURE'

export const REMOVE_MODERATOR = 'REMOVE_MODERATORS'
export const REMOVE_MODERATOR_SUCCESS = 'REMOVE_MODERATORS_SUCCESS'
export const REMOVE_MODERATOR_FAILURE = 'REMOVE_MODERATORS_FAILURE'

export const ADD_GROUP_SHARE = 'ADD_GROUP_SHARE'
export const REMOVE_GROUP_SHARE = 'REMOVE_GROUP_SHARE'
export const GROUP_SHARE_ERROR = 'GROUP_SHARE_ERROR'

export const LEAVE_GROUP = 'LEAVE_GROUP'
export const LEAVE_GROUP_SUCCESS = 'LEAVE_GROUP_SUCCESS'
export const LEAVE_GROUP_FAILURE = 'LEAVE_GROUP_FAILURE'

export const IMPORT_CONTACTS = 'IMPORT_CONTACTS'
export const IMPORT_CONTACTS_SUCCESS = 'IMPORT_CONTACTS_SUCCESS'
export const IMPORT_CONTACTS_FAILURE = 'IMPORT_CONTACTS_FAILURE'

// Attribute Types
export const FETCH_ATTRIBUTE_TYPES = 'FETCH_ATTRIBUTE_TYPES'
export const FETCH_ATTRIBUTE_TYPES_SUCCESS = 'FETCH_ATTRIBUTE_TYPES_SUCCESS'
export const FETCH_ATTRIBUTE_TYPES_FAILURE = 'FETCH_ATTRIBUTE_TYPES_FAILURE'

export const ADD_ATTRIBUTE = 'ADD_ATTRIBUTE'
export const ADD_ATTRIBUTE_SUCCESS = 'ADD_ATTRIBUTE_SUCCESS'
export const ADD_GROUP_ATTRIBUTE_SUCCESS = 'ADD_GROUP_ATTRIBUTE_SUCCESS'
export const ADD_ATTRIBUTE_FAILURE = 'ADD_ATTRIBUTE_FAILURE'

export const EDIT_ATTRIBUTE = 'EDIT_ATTRIBUTE'
export const EDIT_ATTRIBUTE_SUCCESS = 'EDIT_ATTRIBUTE_SUCCESS'
export const EDIT_ATTRIBUTE_FAILURE = 'EDIT_ATTRIBUTE_FAILURE'

export const DELETE_ATTRIBUTE = 'DELETE_ATTRIBUTE'
export const DELETE_ATTRIBUTE_SUCCESS = 'DELETE_ATTRIBUTE_SUCCESS'
export const DELETE_ATTRIBUTE_FAILURE = 'DELETE_ATTRIBUTE_FAILURE'

export const VERIFY_ATTRIBUTE = 'VERIFY_ATTRIBUTE'
export const VERIFY_ATTRIBUTE_SUCCESS = 'VERIFY_ATTRIBUTE_SUCCESS'
export const VERIFY_ATTRIBUTE_FAILURE = 'VERIFY_ATTRIBUTE_FAILURE'

export const RESEND_VERIFY_ATTRIBUTE = 'RESEND_VERIFY_ATTRIBUTE'
export const RESEND_VERIFY_ATTRIBUTE_SUCCESS = 'RESEND_VERIFY_ATTRIBUTE_SUCCESS'
export const RESEND_VERIFY_ATTRIBUTE_FAILURE = 'RESEND_VERIFY_ATTRIBUTE_FAILURE'

// Share Types
export const ENABLE_QR_SHARE = 'ENABLE_QR_SHARE'
export const DISABLE_QR_SHARE = 'DISABLE_QR_SHARE'
export const QR_SHARE_ERROR = 'QR_SHARE_ERROR'

export const GENERATE_QR_PIN = 'GENERATE_QR_PIN'
export const GENERATE_QR_PIN_SUCCESS = 'GENERATE_QR_PIN_SUCCESS'
export const GENERATE_QR_PIN_FAILURE = 'GENERATE_QR_PIN_FAILURE'

export const INVITE = 'INVITE'
export const INVITE_SUCCESS = 'INVITE_SUCCESS'
export const INVITE_FAILURE = 'INVITE_FAILURE'

export const SET_BULK_SHARES = 'SET_BULK_SHARES'
export const ADD_SHARE_BULK = 'ADD_SHARE_BULK'
export const REMOVE_SHARE_BULK = 'REMOVE_SHARE_BULK'
export const SHARE_BULK_ERROR = 'SHARE_BULK_ERROR'

// Util & Settings Types
export const SWIPED = 'SWIPED'
export const REMOVE_ERROR = 'REMOVE_ERROR'

export const UPDATE_QUERY = 'UPDATE_QUERY'
export const CLEAR_QUERY = 'CLEAR_QUERY'

export const UPDATE_SEARCH_TAGS = 'UPDATE_SEARCH_TAGS'
export const CLEAR_SEARCH_TAGS = 'CLEAR_SEARCH_TAGS'

export const LOAD = 'LOAD'
export const LOAD_SUCCESS = 'LOAD_SUCCESS'
export const LOAD_FAILURE = 'LOAD_FAILURE'

export const SETTING_ERROR = 'SETTING_ERROR'
export const ENABLE_NOTIFICATIONS = 'ENABLE_NOTIFICATIONS'
export const DISABLE_NOTIFICAITONS = 'DISABLE_NOTIFICATIONS'
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE'

export const DOWNLOAD_DATA = 'DOWNLOAD_DATA'
export const DOWNLOAD_DATA_SUCCESS = 'DOWNLOAD_DATA_SUCCESS'
export const DOWNLOAD_DATA_FAILURE = 'DOWNLOAD_DATA_FAILURE'

export const DELETE_ACCOUNT = 'DELETE_ACCOUNT'
export const DELETE_ACCOUNT_SUCCESS = 'DELETE_ACCOUNT_SUCCESS'
export const DELETE_ACCOUNT_FAILURE = 'DELETE_ACCOUNT_FAILURE'

export const FETCH_SESSIONS = 'FETCH_SESSIONS'
export const FETCH_SESSIONS_SUCCESS = 'FETCH_SESSIONS_SUCCESS'
export const FETCH_SESSIONS_FAILURE = 'FETCH_SESSIONS_FAILURE'
