// Auth types
export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGOUT = 'LOGOUT'
export const AUTHORIZE = 'AUTHORIZE'

export const CREATE_PROFILE = 'CREATE_PROFILE'
export const CREATE_PROFILE_SUCCESS = 'CREATE_PROFILE_SUCCESS'
export const CREATE_PROFILE_FAILURE = 'CREATE_PROFILE_FAILURE'

export const VERIFY = 'VERIFY'
export const VERIFY_SUCCESS = 'VERIFY_SUCCESS'
export const VERIFY_SUCCESS_AUTH = 'VERIFY_SUCCESS_AUTH'
export const VERIFY_FAILURE = 'VERIFY_FAILURE'

// User Types
export const FETCH_PROFILE = 'FETCH_PROFILE'
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS'
export const FETCH_PROFILE_FAILURE = 'FETCH_PROFILE_FAILURE'

export const UPLOAD_AVATAR = 'UPLOAD_AVATAR'
export const UPLOAD_AVATAR_SUCCESS = 'UPLOAD_AVATAR_SUCCESS'
export const UPLOAD_AVATAR_FAILURE = 'UPLOAD_AVATAR_FAILURE'

// Contact & Group Types
export const FETCH_CONTACT_LIST = 'FETCH_CONTACT_LIST'
export const FETCH_CONTACT_LIST_SUCCESS = 'FETCH_CONTACT_LIST_SUCCESS'
export const FETCH_CONTACT_LIST_FAILURE = 'FETCH_CONTACT_LIST_FAILURE'

export const FETCH_CONTACT = 'FETCH_CONTACT'
export const FETCH_CONTACT_SUCCESS = 'FETCH_CONTACT_SUCCESS'
export const FETCH_CONTACT_FAILURE = 'FETCH_CONTACT_FAILURE'

export const FETCH_GROUP_LIST = 'FETCH_GROUP_LIST'
export const FETCH_GROUP_LIST_SUCCESS = 'FETCH_GROUP_LIST_SUCCESS'
export const FETCH_GROUP_LIST_FAILURE = 'FETCH_GROUP_LIST_FAILURE'

export const FETCH_GROUP = 'FETCH_GROUP'
export const FETCH_GROUP_SUCCESS = 'FETCH_GROUP_SUCCESS'
export const FETCH_GROUP_FAILURE = 'FETCH_GROUP_FAILURE'

export const CREATE_GROUP = 'CREATE_GROUP'
export const CREATE_GROUP_SUCCESS = 'CREATE_GROUP_SUCCESS'
export const CREATE_GROUP_FAILURE = 'CREATE_GROUP_FAILURE'

// Attribute Types
export const FETCH_ATTRIBUTE_TYPES = 'FETCH_ATTRIBUTE_TYPES'
export const FETCH_ATTRIBUTE_TYPES_SUCCESS = 'FETCH_ATTRIBUTE_TYPES_SUCCESS'
export const FETCH_ATTRIBUTE_TYPES_FAILURE = 'FETCH_ATTRIBUTE_TYPES_FAILURE'

export const ADD_ATTRIBUTE = 'ADD_ATTRIBUTE'
export const ADD_ATTRIBUTE_SUCCESS = 'ADD_ATTRIBUTE_SUCCESS'
export const ADD_ATTRIBUTE_FAILURE = 'ADD_ATTRIBUTE_FAILURE'

export const EDIT_ATTRIBUTE = 'EDIT_ATTRIBUTE'
export const EDIT_ATTRIBUTE_SUCCESS = 'EDIT_ATTRIBUTE_SUCCESS'
export const EDIT_ATTRIBUTE_FAILURE = 'EDIT_ATTRIBUTE_FAILURE'

export const DELETE_ATTRIBUTE = 'DELETE_ATTRIBUTE'
export const DELETE_ATTRIBUTE_SUCCESS = 'DELETE_ATTRIBUTE_SUCCESS'
export const DELETE_ATTRIBUTE_FAILURE = 'DELETE_ATTRIBUTE_FAILURE'

export const VERIFY_ATTRIBUTE = 'VERIFY_ATTRIBUTE'
export const VERIFY_ATTRIBUTE_SUCCESS = 'VERIFY_ATTRIBUTE_SUCCESS'
export const VERIFY_ATTRIBUTE_FAILURE = 'VERIFY_ATTRIBUTE_FAILURE'

export const RESEND_VERIFY_ATTRIBUTE = 'RESEND_VERIFY_ATTRIBUTE'
export const RESEND_VERIFY_ATTRIBUTE_SUCCESS = 'RESEND_VERIFY_ATTRIBUTE_SUCCESS'
export const RESEND_VERIFY_ATTRIBUTE_FAILURE = 'RESEND_VERIFY_ATTRIBUTE_FAILURE'

// Share Types
export const SET_SHARE_ATTRIBUTES = 'SET_SHARE_ATTRIBUTES'
export const SET_SHARE_ATTRIBUTES_SUCCESS = 'SET_SHARE_ATTRIBUTES_SUCCESS'
export const SET_SHARE_ATTRIBUTES_FAILURE = 'SET_SHARE_ATTRIBUTES_FAILURE'

export const TOGGLE_SHARE_ATTRIBUTE = 'TOGGLE_SHARE_ATTRIBUTES'
export const TOGGLE_SHARE_ATTRIBUTE_SUCCESS = 'TOGGLE_SHARE_ATTRIBUTES_SUCCESS'
export const TOGGLE_SHARE_ATTRIBUTE_FAILURE = 'TOGGLE_SHARE_ATTRIBUTES_FAILURE'

export const ENABLE_QR_SHARE = 'ENABLE_QR_SHARE'
export const DISABLE_QR_SHARE = 'DISABLE_QR_SHARE'
export const QR_SHARE_ERROR = 'QR_SHARE_ERROR'

export const INVITE = 'INVITE'
export const INVITE_SUCCESS = 'INVITE_SUCCESS'
export const INVITE_FAILURE = 'INVITE_FAILURE'

// Util & Settings Types
export const SWIPED = 'SWIPED'
export const REMOVE_ERROR = 'REMOVE_ERROR'

export const LOAD = 'LOAD'
export const LOAD_SUCCESS = 'LOAD_SUCCESS'
export const LOAD_FAILURE = 'LOAD_FAILURE'

export const SETTING_ERROR = 'SETTING_ERROR'
export const ENABLE_NOTIFICATIONS = 'ENABLE_NOTIFICATIONS'
export const DISABLE_NOTIFICAITONS = 'DISABLE_NOTIFICATIONS'
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE'

export const DOWNLOAD_DATA = 'DOWNLOAD_DATA'
export const DOWNLOAD_DATA_SUCCESS = 'DOWNLOAD_DATA_SUCCESS'
export const DOWNLOAD_DATA_FAILURE = 'DOWNLOAD_DATA_FAILURE'

export const DELETE_ACCOUNT = 'DELETE_ACCOUNT'
export const DELETE_ACCOUNT_SUCCESS = 'DELETE_ACCOUNT_SUCCESS'
export const DELETE_ACCOUNT_FAILURE = 'DELETE_ACCOUNT_FAILURE'

export const FETCH_SESSIONS = 'FETCH_SESSIONS'
export const FETCH_SESSIONS_SUCCESS = 'FETCH_SESSIONS_SUCCESS'
export const FETCH_SESSIONS_FAILURE = 'FETCH_SESSIONS_FAILURE'
