export const SIGN_IN = 'SIGN_IN'
export const SIGN_OUT = 'SIGN_OUT'
export const REGISTER = 'REGISTER'
export const VERIFY = 'VERIFY'
export const FETCH_CONTACTS = 'FETCH_CONTACTS'
export const SWIPED = 'SWIPED'
