// Auth types
export const SIGN_IN = 'SIGN_IN'
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE'
export const SIGN_OUT = 'SIGN_OUT'
export const AUTHORIZE = 'AUTHORIZE'

export const REGISTER = 'REGISTER'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILURE = 'REGISTER_FAILURE'

export const VERIFY = 'VERIFY'
export const VERIFY_SUCCESS = 'VERIFY_SUCCESS'
export const VERIFY_FAILURE = 'VERIFY_FAILURE'

export const FORGOT_PASSWORD = 'FORGOT_PASSWORD'
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS'
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE'

export const VERIFY_PASSWORD_RESET = 'VERIFY_PASSWORD_RESET'
export const VERIFY_PASSWORD_RESET_SUCCESS = 'VERIFY_PASSWORD_RESET_SUCCESS'
export const VERIFY_PASSWORD_RESET_FAILURE = 'VERIFY_PASSWORD_RESET_FAILURE'

export const RESET_PASSWORD = 'RESET_PASSWORD'
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE'

// User Types
export const FETCH_PROFILE = 'FETCH_PROFILE'
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS'
export const FETCH_PROFILE_FAILURE = 'FETCH_PROFILE_FAILURE'

export const FETCH_ATTRIBUTES = 'FETCH_ATTRIBUTES'
export const FETCH_ATTRIBUTES_SUCCESS = 'FETCH_ATTRIBUTES_SUCCESS'
export const FETCH_ATTRIBUTES_FAILURE = 'FETCH_ATTRIBUTES_FAILURE'

// Contact & Group Types
export const FETCH_CONTACT_LIST = 'FETCH_CONTACT_LIST'
export const FETCH_CONTACT_LIST_SUCCESS = 'FETCH_CONTACT_LIST_SUCCESS'
export const FETCH_CONTACT_LIST_FAILURE = 'FETCH_CONTACT_LIST_FAILURE'

export const FETCH_CONTACT = 'FETCH_CONTACT'
export const FETCH_CONTACT_SUCCESS = 'FETCH_CONTACT_SUCCESS'
export const FETCH_CONTACT_FAILURE = 'FETCH_CONTACT_FAILURE'

export const FETCH_GROUP_LIST = 'FETCH_GROUP_LIST'
export const FETCH_GROUP_LIST_SUCCESS = 'FETCH_GROUP_LIST_SUCCESS'
export const FETCH_GROUP_LIST_FAILURE = 'FETCH_GROUP_LIST_FAILURE'

export const FETCH_GROUP = 'FETCH_GROUP'
export const FETCH_GROUP_SUCCESS = 'FETCH_GROUP_SUCCESS'
export const FETCH_GROUP_FAILURE = 'FETCH_GROUP_FAILURE'

// Attribute & Share Types
export const ADD_ATTRIBUTE = 'ADD_ATTRIBUTE'
export const ADD_ATTRIBUTE_SUCCESS = 'ADD_ATTRIBUTE_SUCCESS'
export const ADD_ATTRIBUTE_FAILURE = 'ADD_ATTRIBUTE_FAILURE'

export const EDIT_ATTRIBUTE = 'EDIT_ATTRIBUTE'
export const EDIT_ATTRIBUTE_SUCCESS = 'EDIT_ATTRIBUTE_SUCCESS'
export const EDIT_ATTRIBUTE_FAILURE = 'EDIT_ATTRIBUTE_FAILURE'

export const DELETE_ATTRIBUTE = 'DELETE_ATTRIBUTE'
export const DELETE_ATTRIBUTE_SUCCESS = 'DELETE_ATTRIBUTE_SUCCESS'
export const DELETE_ATTRIBUTE_FAILURE = 'DELETE_ATTRIBUTE_FAILURE'

export const SHARE_ATTRIBUTES = 'SHARE_ATTRIBUTES'
export const SHARE_ATTRIBUTES_SUCCESS = 'SHARE_ATTRIBUTES_SUCCESS'
export const SHARE_ATTRIBUTES_FAILURE = 'SHARE_ATTRIBUTES_FAILURE'

export const BUILD_COLLECTIONS = 'BUILD_COLLECTIONS'

// Normal Types
export const SWIPED = 'SWIPED'
export const NONE = 'NONE'

export const FETCH_SETTINGS = 'FETCH_SETTINGS'
export const FETCH_SETTINGS_SUCCESS = 'FETCH_SETTINGS_SUCCESS'
export const FETCH_SETTINGS_FAILURE = 'FETCH_SETTINGS_FAILURE'
